blank_issues_enabled: false
contact_links:
  - name: Security policy
    url: https://github.com/cubetribe/NGINX_Master6000/blob/main/.github/SECURITY.md
    about: Please use the security policy for vulnerabilities and sensitive reports.
